{{- if and .Values.storage.enabled .Values.storage.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.storage.serviceAccount.name | default (printf "%s-storage" (include "supabase.fullname" .)) }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
    supabaseComponent: {{ include "supabase.fullname" . }}-storage
  {{- with .Values.storage.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}