{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.fullname" . }}-auth
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  type: {{ .Values.auth.service.type }}
  ports:
  - port: {{ .Values.auth.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "supabase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth
{{- end }}