{{- if and .Values.kong.enabled .Values.kong.ingress.enabled }}
{{- include "supabase.ingress" (dict "component" "kong" "ingress" .Values.kong.ingress "Values" .Values "Release" .Release "Chart" .Chart) }}
{{- end }}