{{- if .Values.vector.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "supabase.fullname" . }}-reader
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    resourceNames:
      - {{ include "supabase.fullname" . }}-*
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "supabase.fullname" . }}-view
subjects:
  - kind: ServiceAccount
    name: {{ .Values.vector.serviceAccount.name | default "default" }}
    namespace: {{ include "supabase.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "supabase.fullname" . }}-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}