{{- if and .Values.imgproxy.enabled .Values.imgproxy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.imgproxy.serviceAccount.name | default (printf "%s-imgproxy" (include "supabase.fullname" .)) }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: imgproxy
    supabaseComponent: {{ include "supabase.fullname" . }}-imgproxy
  {{- with .Values.imgproxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}