{{- if .Values.realtime.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.fullname" . }}-realtime
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: realtime
spec:
  type: {{ .Values.realtime.service.type }}
  ports:
  - port: {{ .Values.realtime.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "supabase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: realtime
{{- end }}