{{- if and .Values.realtime.enabled .Values.realtime.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.realtime.serviceAccount.name | default (printf "%s-realtime" (include "supabase.fullname" .)) }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: realtime
    supabaseComponent: {{ include "supabase.fullname" . }}-realtime
  {{- with .Values.realtime.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}