{{- if and .Values.functions.enabled .Values.functions.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.functions.serviceAccount.name | default (printf "%s-functions" (include "supabase.fullname" .)) }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: functions
    supabaseComponent: {{ include "supabase.fullname" . }}-functions
  {{- with .Values.functions.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}