{{- if and .Values.analytics.enabled .Values.analytics.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.analytics.serviceAccount.name | default (printf "%s-analytics" (include "supabase.fullname" .)) }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
    supabaseComponent: {{ include "supabase.fullname" . }}-analytics
  {{- with .Values.analytics.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}