{{- if and .Values.rest.enabled .Values.rest.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rest.serviceAccount.name | default (printf "%s-rest" (include "supabase.fullname" .)) }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: rest
    supabaseComponent: {{ include "supabase.fullname" . }}-rest
  {{- with .Values.rest.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}