{{- if .Values.meta.enabled }}
{{- include "supabase.service" (dict "component" "meta" "service" .Values.meta.service "ports" (list (dict "port" .Values.meta.service.port "targetPort" .Values.meta.service.port "protocol" "TCP" "name" "http")) "extraAnnotations" .Values.meta.extraAnnotations "Values" .Values "Release" .Release "Chart" .Chart) }}
{{- end }}