{{- if and .Values.meta.enabled .Values.meta.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.meta.serviceAccount.name | default (printf "%s-meta" (include "supabase.fullname" .)) }}
  namespace: {{ include "supabase.namespace" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: meta
    supabaseComponent: {{ include "supabase.fullname" . }}-meta
  {{- with .Values.meta.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}