name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/release.yaml'
      - 'CHANGELOG.md'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Initialize gh-pages branch
        run: |
          # Fetch all branches including gh-pages
          git fetch origin gh-pages:gh-pages || true

          # Check if gh-pages branch exists
          if ! git ls-remote --heads origin gh-pages | grep -q gh-pages; then
            echo "Creating gh-pages branch..."
            # Create an empty gh-pages branch
            git checkout --orphan gh-pages
            # Remove all files
            git rm -rf .
            # Create a basic index.yaml
            cat > index.yaml << EOF
          apiVersion: v1
          entries: {}
          EOF
            # Commit and push the new branch
            git add index.yaml
            git commit -m "Initialize gh-pages branch with empty index"
            git push origin gh-pages
            # Switch back to main branch
            git checkout main
          else
            echo "gh-pages branch already exists"
            # Ensure we have the latest gh-pages branch
            git fetch origin gh-pages:gh-pages
          fi

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Verify Helm OCI support
        run: |
          helm version
          echo "Helm OCI support verified"

      - name: Install chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Helm chart to GHCR
        run: |
          # Check if chart package exists
          if [ ! -f .cr-release-packages/supabase-*.tgz ]; then
            echo "Error: No chart package found in .cr-release-packages/"
            exit 1
          fi

          # Get the chart version from the packaged chart
          CHART_VERSION=$(helm show chart .cr-release-packages/supabase-*.tgz | grep '^version:' | cut -d' ' -f2)
          echo "Pushing chart version: $CHART_VERSION to GHCR"

          # List the chart package for verification
          ls -la .cr-release-packages/

          # Push the chart to GHCR
          helm push .cr-release-packages/supabase-*.tgz oci://ghcr.io/${{ github.repository_owner }}/charts

          echo "Successfully pushed chart to GHCR"
          echo "Chart available at: oci://ghcr.io/${{ github.repository_owner }}/charts/supabase:$CHART_VERSION"

      - name: Create Release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's Changed

            This release includes the following changes:

            - Updated Supabase services to latest versions
            - Improved configuration options
            - Enhanced documentation

            ## Installation

            ```bash
            helm repo add supabase-helm https://wayli-app.github.io/supabase-helm
            helm repo update
            helm install my-supabase supabase-helm/supabase
            ```

            ## Breaking Changes

            None in this release.

            ## Migration Guide

            No migration required for this release.
          draft: false
          prerelease: false
